### ISSUE TITLE
Sequence Ontology (SO) properties do not resolve

### ISSUE THREAD

**Issue by arnikz** [OBOFoundry/purl.obolibrary.org#253] opened 2016-10-19 18:52 UTC
See previously posted issue [here](https://github.com/OntoZoo/ontobee/issues/91). Thanks,

**Comment by cmungall** [comment] 2016-10-20 21:10
I recommend SO uses the standard RO/BFO properties

If the source version of SO is .obo, there is a quick fix for this. Just add an xref next to each term (for the gory details see owlcollab.github.io/oboformat/doc/obo-syntax.html#4.4)

See any other ontology for details. E.g. in GO:

```
[Typedef]
id: part_of
name: part of
xref: BFO:0000050
is_transitive: true
```

**Comment by arnikz** [comment] 2016-10-25 21:48
Hi @cmungall. I agree, but haven't heard from the SO team so far.

**Comment by mcourtot** [comment] 2017-02-01 14:18
Duplicate of https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/380
Closing this ticket as it is not a PURL issue, rather something the SO developers should address.

**Closed by mcourtot** 2017-02-01 14:18 UTC
