### ISSUE TITLE
Fresh out of the box, should tests fail?

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/purl.obolibrary.org#143] opened 2016-01-21 19:50 UTC
I am trying to use a fresh installation as described in the readme. When I run make I get

<pre>
....
at temp/obo/obo/.htaccess > temp/obo/.htaccess
echo '' >> temp/obo/.htaccess
echo '### Generated from project configuration files' >> temp/obo/.htaccess
echo '' >> temp/obo/.htaccess
cat temp/base_redirects/*.htaccess >> temp/obo/.htaccess
cat temp/products/*.htaccess >> temp/obo/.htaccess
cat temp/terms/*.htaccess >> temp/obo/.htaccess
rm -rf temp/obo/obo
rm -rf temp/obo/OBO
rm -rf www/obo
rm: cannot remove 'www/obo/vario': Directory not empty
rm: cannot remove 'www/obo/vhog': Directory not empty
rm: cannot remove 'www/obo/wbbt': Directory not empty
...
</pre>

When I run make test I get:

<pre>
...
tools/test.py --delay=0.01 localhost config/xco.yml tests/development/xco.tsv
tools/test.py --delay=0.01 localhost config/zfa.yml tests/development/zfa.tsv
tools/test.py --delay=0.01 localhost config/zfs.yml tests/development/zfs.tsv
FAIL	/obo/aeo.owl	302	http://www.berkeleybop.org/ontologies/aeo.owl	302	http://purl.oclc.org/obo/aeo.owl
FAIL	/obo/aeo.obo	302	http://www.berkeleybop.org/ontologies/aeo.obo	302	http://purl.oclc.org/obo/aeo.obo
...
</pre>

I will go back and read the instructions. Perhaps I missed a step?

**Comment by alanruttenberg** [comment] 2016-01-21 19:55
What i did:
<pre>
git clone https://github.com/OBOFoundry/purl.obolibrary.org.git
cd purl.obolibrary.org/tools
vagrant up
</pre>
I didn't have ansible installed, so I installed it (brew install ansible) and then ran 
<pre>
vagrant provision
</pre>
and then continued with
<pre>
vagrant ssh
cd /var/www/purl.obolibrary.org
make
make all test
</pre>

**Comment by jamesaoverton** [comment] 2016-01-21 20:01
Ok, thanks. I'm probably the only one who has set this up so far, so there's bound to be some problems.

I'll add "install Ansible" to the "Development and Testing" section.

I'm building a fresh VM now to see if I can duplicate.

**Comment by jamesaoverton** [comment] 2016-01-21 20:07
Yes, I'm seeing `rm: cannot remove 'www/obo/vario': Directory not empty` when I run `make` after the first time. Looking into it.

**Comment by jamesaoverton** [comment] 2016-01-21 20:19
The `rm -rf www/obo` at line 139 is failing, but I don't understand why. Within the VM, `rm` keeps giving me the `Directory not empty` error, but I don't see any files.

If I remove the `www/obo` directory using Finder on my host MacBook, then `make all test` works fine again, once, before returning to the same problem.

**Comment by jamesaoverton** [comment] 2016-01-21 20:29
It seems to be only some of the project directories that resist deletion. I don't see a pattern, though.

On my host machine I can see that there are `.htaccess` files in these directories, but I can't see those files from within the VM. The problem is similar to this StackOverflow response: http://askubuntu.com/a/638597. Vagrant is mounting part of the host filesystem into the VM (which is convenient when editing the code) at `/var/www/purl.obolibrary.org`. I expect there's a problem on that layer.

**Comment by jamesaoverton** [comment] 2016-01-21 20:35
Maybe this very old VirtualBox issue: https://www.virtualbox.org/ticket/8761

**Comment by jamesaoverton** [comment] 2016-01-21 21:00
I'm convinced that we're seeing VirtualBox issue [#8761](https://www.virtualbox.org/ticket/8761), but I don't have a great solution. It should not affect deployments to servers.

Vagrant has four options for [synced-folders](https://www.vagrantup.com/docs/synced-folders/). The default is VirtualBox synced folders, which is the source of the problem. Unfortunately, two of the other Vagrant options aren't cross-platform compatible (NFS and SMB). The final option is `rsync`, which works on Unix platforms by default and on Windows using Cygwin. Syncing requires an extra step, and is not two-way. Maybe we don't want to bother.

But I did make `rsync` work by editing the `tools/Vagrantfile` and adding `type: "rsync"` to line 9:

    config.vm.synced_folder "..", "/var/www/purl.obolibrary.org", type: "rsync"

then running `vagrant reload` to make the setting stick. You have to run `vagrant rsync` or `vagrant rsync-auto` to copy files from host to VM.

[This article](http://www.midwesternmac.com/blogs/jeff-geerling/vagrant-nfs-shared-folders) suggests switching NFS or SMB based on platform.

**Comment by jamesaoverton** [comment] 2016-01-21 21:06
It might be better to modify the `Makefile`, replacing `rm -rf www/obo` with a move and then multiple `rm` calls.

**Comment by jamesaoverton** [comment] 2016-01-21 21:29
I couldn't make the `Makefile` idea work.

**Comment by alanruttenberg** [comment] 2016-01-21 21:35
Ok. I'll have a poke at it. Thanks for looking into this!

**Comment by jamesaoverton** [comment] 2016-01-25 14:32
My new idea is not to bother deleting `www/obo`. Instead, we can move it to a dated folder under `temp/`. The amount of data is tiny, and it lets us revert to or diff against previous versions. The shared folder configuration doesn't have to change.

This doesn't avoid the problem completely, so I can add a warning to the docs.

Code for the `Makefile`. Before line 139:

    # Get name of a dated-backup directory, in a portable way.
    BACKUP = temp/obo-$(shell python -c "import time,os;print(time.strftime('%Y%m%d-%H%M%S',time.gmtime(os.path.getmtime('www/obo'))))")

Change line 139:

    test -e www/obo && mv www/obo $(BACKUP)

**Comment by cmungall** [comment] 2016-01-25 16:27
FWIW. Only got round to testing. On OS X.

`make` works, browser test with class purl works, `make all test` fails with same phenotype

**Comment by jamesaoverton** [comment] 2016-02-05 18:41
This should be fixed by commit fea6aae. If not, please reopen.

**Closed by jamesaoverton** 2016-02-05 18:41 UTC
